# Generated by Django 3.1 on 2021-06-07 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelGlassWithDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('model_code', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
                ('model_desc', models.CharField(max_length=200, null=True)),
                ('defect_name1', models.CharField(max_length=200, null=True)),
                ('defect_name2', models.CharField(max_length=200, null=True)),
                ('defect_name3', models.CharField(max_length=200, null=True)),
                ('defect_name4', models.CharField(max_length=200, null=True)),
                ('defect_name5', models.CharField(max_length=200, null=True)),
                ('date_select', models.DateField()),
                ('shift', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
    ]
