# Generated by Django 3.1 on 2021-06-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_modelglasswithdefect_for_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelglasswithdefect',
            name='number_glass',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelglasswithdefect',
            name='point_defect',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelglasswithdefect',
            name='status_glass',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
