# Generated by Django 3.1 on 2021-06-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_modelglasswithdefect_id_glass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelglasswithdefect',
            name='id_glass',
            field=models.IntegerField(),
        ),
    ]
